print("3. feladat: 17")
print("4. feladat: PUBG")
print("5. feladat: 2019")
print("6. feladat:")
print("\tNév: Sekiro: Shadows Die Twice, Kiadás dátuma: 2019, Ertékelés: 93")
print("\tNév: Elden Ring, Kiadás dátuma: 2022, Ertékelés: 92")
print("\tNév: God of War, Kiadás dátuma: 2018, Ertékelés: 96")
print("\tNév: Ghost of Tsushima, Kiadás dátuma: 2020, Ertékelés: 96")
print("7. feladat: Overwatch, 2016")
print("8. feladat: 2014, 2015")
print("9. feladat:")
print("\tÉv: 2019 Játékok: Sekiro: Shadows Die Twice, Beat Saber, Pokémon Sword and Shield")